src/Entity/Contents.php
<?php

namespace App\Entity;

use App\Repository\ContentsRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ContentsRepository::class)
 * @Vich\Uploadable
 */
class Contents
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    public $content;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $content_status;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $comment_status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content_slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $content_password;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $content_type;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="content", orphanRemoval=true)
     */
    private $comment_count;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    public $content_image;

    public $ShortContent;

    public $Tags;

    public $Price;

    public $DiscountedPrice;

    public $WeightDimension;

    public $Weight;

    public $LengthDimension;

    public $Length;

    public $StockStatus;

    public $ProductCount;

    public $Note;

//    /**
//     * @ORM\OneToMany(targetEntity=Attachment::class, mappedBy="contents",cascade={"persist", "remove"})
//     */
//    private $attachments;

    /**
     * @ORM\OneToMany(targetEntity=ContentsCategories::class, mappedBy="content",cascade={"persist", "remove"})
     */
    private $contentsCategories;


    public function __construct()
    {
        $this->comment_count = new ArrayCollection();
       // $this->attachments = new ArrayCollection();
        $this->contentsCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?Users
    {
        return $this->author;
    }

    public function setAuthor(?Users $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getContentStatus(): ?string
    {
        return $this->content_status;
    }

    public function setContentStatus(string $content_status): self
    {
        $this->content_status = $content_status;

        return $this;
    }

    public function getCommentStatus(): ?string
    {
        return $this->comment_status;
    }

    public function setCommentStatus(string $comment_status): self
    {
        $this->comment_status = $comment_status;

        return $this;
    }

    public function getContentSlug(): ?string
    {
        return $this->content_slug;
    }

    public function setContentSlug(string $content_slug): self
    {
        $this->content_slug = $content_slug;

        return $this;
    }

    public function getContentPassword(): ?string
    {
        return $this->content_password;
    }

    public function setContentPassword(?string $content_password): self
    {
        $this->content_password = $content_password;

        return $this;
    }

    public function getContentType(): ?string
    {
        return $this->content_type;
    }

    public function setContentType(string $content_type): self
    {
        $this->content_type = $content_type;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getCommentCount(): Collection
    {
        return $this->comment_count;
    }

    public function addCommentCount(Comments $commentCount): self
    {
        if (!$this->comment_count->contains($commentCount)) {
            $this->comment_count[] = $commentCount;
            $commentCount->setContentId($this);
        }

        return $this;
    }

    public function removeCommentCount(Comments $commentCount): self
    {
        if ($this->comment_count->removeElement($commentCount)) {
            // set the owning side to null (unless already changed)
            if ($commentCount->getContentId() === $this) {
                $commentCount->setContentId(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->content_image;
    }

    public function setImage(?string $content_image): self
    {
        $this->content_image = $content_image;

        return $this;
    }

    public function getTags()
    {
    }

    public function getPrice()
    {
    }

    public function getDiscountedPrice()
    {
    }

    public function getWeightDimension()
    {
    }

    public function getWeight()
    {
    }

    public function getLengthDimension()
    {
    }

    public function getLength()
    {
    }

    public function getStockStatus()
    {
    }

    public function getProductCount()
    {
    }

    public function getNote()
    {
    }

    public function getShortContent()
    {
    }

    /**
     * @return Collection<int, Attachment>
     */
    public function getAttachments(): Collection
    {
        return $this->attachments;
    }

    public function addAttachment(Attachment $attachment): self
    {
        if (!$this->attachments->contains($attachment)) {
            $this->attachments[] = $attachment;
            $attachment->setContents($this);
        }

        return $this;
    }

    public function removeAttachment(Attachment $attachment): self
    {
        if ($this->attachments->removeElement($attachment)) {
            // set the owning side to null (unless already changed)
            if ($attachment->getContents() === $this) {
                $attachment->setContents(null);
            }
        }

        return $this;
    }

    public $Categories;

    public function getCategories()
    {
        return $this->Categories;
    }

    public function setCategories($category)
    {
        $this->Categories = $category;
    }

    /**
     * @return Collection<int, ContentsCategories>
     */
    public function getContentsCategories(): Collection
    {
        return $this->contentsCategories;
    }

    public function addContentsCategory(ContentsCategories $contentsCategory): self
    {
        if (!$this->contentsCategories->contains($contentsCategory)) {
            $this->contentsCategories[] = $contentsCategory;
            $contentsCategory->setContent($this);
        }

        return $this;
    }

    public function removeContentsCategory(ContentsCategories $contentsCategory): self
    {
        if ($this->contentsCategories->removeElement($contentsCategory)) {
            // set the owning side to null (unless already changed)
            if ($contentsCategory->getContent() === $this) {
                $contentsCategory->setContent(null);
            }
        }

        return $this;
    }

    public function getContentImage(): ?string
    {
        return $this->content_image;
    }

    public function setContentImage(?string $content_image): self
    {
        $this->content_image = $content_image;

        return $this;
    }


}

src/Entity/Settings.php
<?php

namespace App\Entity;

use App\Repository\SettingsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SettingsRepository::class)
 */
class Settings
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $site_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $site_description;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $admin_email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $membership;

    /**
     * @ORM\Column(type="integer")
     */
    private $content_count_limitation;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $support_email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $shop_address_one;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $shop_address_two;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $support_number_one;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $support_number_two;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $linkedin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSiteTitle(): ?string
    {
        return $this->site_title;
    }

    public function setSiteTitle(string $site_title): self
    {
        $this->site_title = $site_title;

        return $this;
    }

    public function getSiteDescription(): ?string
    {
        return $this->site_description;
    }

    public function setSiteDescription(string $site_description): self
    {
        $this->site_description = $site_description;

        return $this;
    }

    public function getAdminEmail(): ?string
    {
        return $this->admin_email;
    }

    public function setAdminEmail(string $admin_email): self
    {
        $this->admin_email = $admin_email;

        return $this;
    }

    public function getMembership(): ?bool
    {
        return $this->membership;
    }

    public function setMembership(bool $membership): self
    {
        $this->membership = $membership;

        return $this;
    }

    public function getContentCountLimitation(): ?int
    {
        return $this->content_count_limitation;
    }

    public function setContentCountLimitation(int $content_count_limitation): self
    {
        $this->content_count_limitation = $content_count_limitation;

        return $this;
    }

    public function getSupportEmail(): ?string
    {
        return $this->support_email;
    }

    public function setSupportEmail(string $support_email): self
    {
        $this->support_email = $support_email;

        return $this;
    }

    public function getShopAddressOne(): ?string
    {
        return $this->shop_address_one;
    }

    public function setShopAddressOne(string $shop_address_one): self
    {
        $this->shop_address_one = $shop_address_one;

        return $this;
    }

    public function getShopAddressTwo(): ?string
    {
        return $this->shop_address_two;
    }

    public function setShopAddressTwo(?string $shop_address_two): self
    {
        $this->shop_address_two = $shop_address_two;

        return $this;
    }

    public function getSupportNumberOne(): ?string
    {
        return $this->support_number_one;
    }

    public function setSupportNumberOne(string $support_number_one): self
    {
        $this->support_number_one = $support_number_one;

        return $this;
    }

    public function getSupportNumberTwo(): ?string
    {
        return $this->support_number_two;
    }

    public function setSupportNumberTwo(?string $support_number_two): self
    {
        $this->support_number_two = $support_number_two;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_settings.siteTitle }}{% endblock %}
{% block stylesheets %}
    <!-- Bootstrap core CSS -->
    {{ encore_entry_link_tags('app') }}
    <style></style>
{% endblock %}
        {% block body %}
            <!-- Start Banner Hero -->
            <div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
                <ol class="carousel-indicators">
                    {% if sliders %}
                        {% for s in sliders %}
                            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="{{ s.id }}"
                                {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    {% endif %}
                </ol>
                <div class="carousel-inner">
                    {% if sliders %}
                        {% for s in sliders %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <div class="container">
                                    <div class="row p-5">
                                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                                            <img class="img-fluid"
                                                 src="{{ asset('uploads/images/sliders/'~ s.imageFile) }}"
                                                 alt="{{ s.title }}">
                                        </div>
                                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                                            <div class="text-align-left align-self-center">
                                                <h1 class="h1 text-success">{{ s.title }}</h1>
                                                <h3 class="h2">{{ s.subTitle }}</h3>
                                                <p>{{ s.content|raw }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="#template-mo-zay-hero-carousel"
                   role="button" data-bs-slide="prev">
                    <i class="fas fa-chevron-left"></i>
                </a>
                <a class="carousel-control-next text-decoration-none w-auto pe-3" href="#template-mo-zay-hero-carousel"
                   role="button" data-bs-slide="next">
                    <i class="fas fa-chevron-right"></i>
                </a>
            </div>
            <!-- End Banner Hero -->

            <!-- Start Categories of The Month -->
            <section class="container py-5">
                <div class="row text-center pt-3">
                    <div class="col-lg-6 m-auto">
                        <h1 class="h1">Categories of The Month</h1>
                        <p>
                            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                            deserunt mollit anim id est laborum.
                        </p>
                    </div>
                </div>
                <div class="row">
                    {% if categories %}
                        {% for c in categories %}
                            <div class="col-12 col-md-4 p-5 mt-3">
                                <a href="/{{ c.slug }}">
                                    <img src="{{ asset('uploads/images/categories/'~c.image) }}" alt="{{ c.name }}"
                                         class="rounded-circle img-fluid border">
                                </a>
                                <h5 class="text-center mt-3 mb-3">{{ c.name }}</h5>
                                <p class="text-center"><a class="btn btn-success" href="/{{ c.slug }}">Go Shop</a></p>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </section>
            <!-- End Categories of The Month -->


            <!-- Start Featured Product -->
            <section class="bg-light">
                <div class="container py-5">
                    <div class="row text-center py-3">
                        <div class="col-lg-6 m-auto">
                            <h1 class="h1">Featured Product</h1>
                            <p>
                                Reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                                Excepteur sint occaecat cupidatat non proident.
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        {% if products %}
                            {% for p in products %}
                                <div class="col-12 col-md-4 mb-4">
                                    <div class="card h-100">
                                        <a href="/product/{{ p.slug }}">
                                            <img src="{{ asset('uploads/images/products/'~p.imageFile) }}"
                                                 class="card-img-top"
                                                 alt="{{ p.title }}">
                                        </a>
                                        <div class="card-body">
                                            <ul class="list-unstyled d-flex justify-content-between">
                                                <li>
                                                    {% for i in range(1,random(2,5)) %}
                                                        <i class="text-warning fa fa-star"></i>
                                                    {% endfor %}
                                                </li>
                                                <li class="text-muted text-right">
                                                    {% if p.discountedPrice > 0 %}
                                                        ${{ p.discountedPrice }}
                                                    {% else %}
                                                        ${{ p.price }}
                                                    {% endif %}
                                                </li>
                                            </ul>
                                            <a href="product/{{ p.slug }}"
                                               class="h2 text-decoration-none text-dark">{{ p.title }}</a>
                                            <p class="card-text">{{ p.shortContent|raw }}</p>
                                            <p class="text-muted">Reviews ({{ random(0, 1000) }})</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </section>
            <!-- End Featured Product -->


        {% endblock %}
    {% block footer %}
      {% include('footer.html.twig') %}
    {% endblock %}