src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 */
class Users implements UserInterface, PasswordAuthenticatedUserInterface {

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $user_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string")
     */
    private $roles;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $register_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $update_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Salt;

    public function getId(): ?int {
        return $this->id;
    }

    public function getEmail(): ?string {
        return $this->email;
    }

    public function setEmail(string $email): self {
        $this->email = $email;

        return $this;
    }

    public function getFirstName(): ?string {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self {
        $this->last_name = $last_name;

        return $this;
    }

    public function getUserName(): ?string {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self {
        $this->user_name = $user_name;

        return $this;
    }

    public function getPassword(): ?string {
        return $this->password;
    }

    public function setPassword(string $password): self {
        $this->password = $password;

        return $this;
    }

    public function getRoles(): ?array {
        if($this->roles == 1){
            return array('ROLE_ADMIN');
        }
        else{
            return array('ROLE_USER');
        }
    }

    public function setRoles(string $roles): self {
        $this->roles = $roles;

        return $this;
    }

    public function getStatus(): ?int {
        return $this->status;
    }

    public function setStatus(int $status): self {
        $this->status = $status;

        return $this;
    }

    public function getRegisterAt(): ?DateTimeInterface {
        return $this->register_at;
    }

    public function setRegisterAt(DateTimeInterface $register_at): self {
        $this->register_at = $register_at;

        return $this;
    }

    public function getUpdateAt(): ?DateTimeInterface {
        return $this->update_at;
    }

    public function setUpdateAt(?DateTimeInterface $update_at): self {
        $this->update_at = $update_at;

        return $this;
    }

    public function getSalt() {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return $this->Salt;
    }

    public function eraseCredentials() {
        
    }

    public function setSalt(string $Salt): self {
        $this->Salt = $Salt;

        return $this;
    }
    
}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UsersType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options): void {
        $builder
                ->add('email')
                ->add('first_name')
                ->add('last_name')
                ->add('user_name')
                ->add('password', PasswordType::class, array('label' => 'Password'))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void {
        $resolver->setDefaults([
            'data_class' => Users::class,
        ]);
    }

}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use App\Service\MessageGenerator;
use App\bundles\date\show_date;

/**
 * @Route("/users")
 */
class UsersController extends AbstractController {

    private $message;
    private $date;

    public function __construct(MessageGenerator $message, show_date $date) {
        $this->message = $message->getHappyMessage();
        $this->date = $date->show();
    }

    /**
     * @Route("/", name="app_users_index", methods={"GET"})
     */
    public function index(UsersRepository $usersRepository): Response {
        return $this->render('users/index.html.twig', [
                    'users' => $usersRepository->findAll(),
                    'message' => $this->message,
                    'date' => $this->date,
        ]);
    }

    /**
     * @Route("/new", name="app_users_new", methods={"GET", "POST"})
     */
    public function new(Request $request, UsersRepository $usersRepository, UserPasswordHasherInterface $passwordHasher): Response {
        $user = new Users();

        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //Hashing password 
            $hash_password = $passwordHasher->hashPassword(
                    $user,
                    $user->getPassword(),
            );
            $user->setPassword($hash_password);
            //َAdding user role. One is admin and two is user.
            $user->setRoles(2);
            $usersRepository->add($user);
            return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('users/new.html.twig', [
                    'user' => $user,
                    'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_users_show", methods={"GET"})
     */
    public function show(Users $user): Response {
        return $this->render('users/show.html.twig', [
                    'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_users_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Users $user, UsersRepository $usersRepository): Response {
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $usersRepository->add($user);
            return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('users/edit.html.twig', [
                    'user' => $user,
                    'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_users_delete", methods={"POST"})
     */
    public function delete(Request $request, Users $user, UsersRepository $usersRepository): Response {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $usersRepository->remove($user);
        }

        return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * 
     * This method looks for a user by email. It will return false if the user 
     * can't be found.
     * @param type $email
     * @return boolean
     */
    public static function get_user_by_email($email,$usersRepository) {
        $user = $usersRepository->findOneByEmail($email);
        if (false !== $user && !is_null($user)) {
            return $user;
        } else {
            return false;
        }
    }
    
    public static function get_user_by_user_name($user_name,$usersRepository) {
        $user = $usersRepository->findOneByUserName($user_name);
        if (false !== $user && !is_null($user)) {
            return $user;
        } else {
            return false;
        }
    }

}

templates/users/_delete_form.html.twig
<form method="post" action="{{ path('app_users_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Users{% endblock %}

{% block body %}
    <h1>Edit Users</h1>

    {{ include('users/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_users_index') }}">back to list</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users index{% endblock %}

{% block body %}
    <h1>Users index</h1>
    <h2>{{ message }}</h2>
    <h2>{{ date }}</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>User_name</th>
                <th>Password</th>
                <th>Roles</th>
                <th>Status</th>
                <th>Register_at</th>
                <th>Update_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.userName }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.roles.0 }}</td>
                <td>{{ user.status }}</td>
                <td>{{ user.registerAt ? user.registerAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.updateAt ? user.updateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_users_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_users_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_users_new') }}">Create new</a>
{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Users{% endblock %}

{% block body %}
    <h1>Create new Users</h1>

    {{ include('users/_form.html.twig') }}

    <a href="{{ path('app_users_index') }}">back to list</a>
{% endblock %}

templates/users/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
    <h1>Users</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>User_name</th>
                <td>{{ user.userName }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles.0 }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ user.status }}</td>
            </tr>
            <tr>
                <th>Register_at</th>
                <td>{{ user.registerAt ? user.registerAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Update_at</th>
                <td>{{ user.updateAt ? user.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_users_index') }}">back to list</a>

    <a href="{{ path('app_users_edit', {'id': user.id}) }}">edit</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}